### ISSUE TITLE
support nodejs 5

### ISSUE THREAD

**Issue by evilebottnawi** [nfroidure/ttf2woff2#15]

**Comment by nfroidure** [comment]
Will be resolved with https://github.com/nfroidure/ttf2woff2/issues/11

**Comment by jfleblanc** [comment]
Any idea when you will be able to resolve this issue @nfroidure ? Otherwise, thank very much for your work!

**Comment by nfroidure** [comment]
Just converted the addon to use nan, looks like the Node 5 build is now ok: https://travis-ci.org/nfroidure/ttf2woff2/jobs/89946235
