### ISSUE TITLE
tt2woff2 triggers antivirus

### ISSUE THREAD

**Issue by dudewad** [nfroidure/ttf2woff2#17]
I installed ttf2woff2 automatically as a dependency of grunt-webfont. Attempting to run grunt-webfont then runs ttf2woff2 which triggers an AVG quarantine.

The affected file is ttf2woff2/jssrc/ttf2woff2.js (the minified file)

I have no way to run this without disabling my antivirus or whitelisting the file, which, if I switch machines (or one of my team members tries to use our build process) causes obvious annoyances.

AVG Info:

Thread: Virus identified HTML/Framer.CU  (links to this page: http://www.avgthreatlabs.com/virus-and-malware-information/pu/free/?utm_source=TDPU&utm_medium=RS&CTRY=us&LNG=us&PRTYPE=AVF&V=2016&AI=-1&BE=21198874&IDNT=QEVJRF9JZF92aXJ8JW5hbWUlPUhUTUwvRnJhbWVyLkNV&IDN=YzpcZGV2XHNlcnZlclx3YW1wXHd3d1xyYXpvcmZpc2hcaW50ZWxcYW50aGVtXG5vZGVfbW9kdWxlc1xncnVudC13ZWJmb250XG5vZGVfbW9kdWxlc1x0dGYyd29mZjJcanNzcmNcdHRmMndvZmYyLmpz)

Object name: [long-ass-path]/grunt-webfont/node-modules/ttf2woff2/jssrc/ttf2woff2.js

Worst of all, it doesn't give me the option to whitelist. I have to do that manually.
I'd consider this a breaking issue, but I don't know if there's anything you can do about it.

**Comment by nfroidure** [comment]
Already discussed here https://github.com/nfroidure/ttf2woff2/issues/7#issuecomment-125086036

Reporting the issue to AVG is probably our only option since it is an Emscripten build and i have no way to fix it.

Another option could be to completely rewrite the emscripten wrapper to use embind http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/embind.html

**Comment by dudewad** [comment]
Yeah it seems like you're kinda stuck given the approach taken.
Thanks for letting me know.

**Comment by nfroidure** [comment]
Can you confirm this new Emscripten build isn't catched by AVG ? https://github.com/nfroidure/ttf2woff2/commit/24ec907cfc898bd9f295abdee52928a68e75f221

**Comment by dudewad** [comment]
I'll give it a shot.

**Comment by deepu105** [comment]
I'm using version 2.0.3 and its still caught by AVG as virus
