### ISSUE TITLE
Update Travis CI to also test an OS X build

### ISSUE THREAD

**Issue by Psiablo** [nfroidure/ttf2woff2#19]
Instead of waiting for a OS X user to verify that things are working on new PRs/bug fixes, it would be nice to have Travis CI do it for us.

I _think_ we could get this accomplished. It's going to require running a script to check if we are `darwin` and if so install some dependencies with homebrew.

I can investigate getting this working in some spare time.

**Comment by nfroidure** [comment]
:+1:

**Comment by Psiablo** [comment]
See PR #21.

**Comment by Psiablo** [comment]
Closing issue. Complete.
