### ISSUE TITLE
it's error

### ISSUE THREAD

**Issue by guohuihot** [nfroidure/ttf2woff2#23]
![image](https://cloud.githubusercontent.com/assets/3119995/12082442/ce5ade54-b2cd-11e5-9572-26bb3e34edaf.png)

**Comment by nfroidure** [comment]
Please provide me the inputted TTF font.

**Comment by guohuihot** [comment]
![image](https://cloud.githubusercontent.com/assets/3119995/12086146/40295e46-b302-11e5-816d-10344b14c545.png)
This is OK

**Comment by RobeeeJay** [comment]
I'm having what I think is a similar issue, for some reason even though I'm not using gulp-iconfont and indirectly ttf2woff2, whenever Browserify is throwing an error it's being caught by ttf2woff2 and re-thrown there spamming the same message as above.

Does anyone know what in this module is wrongly catching errors outside of it? Currently having to run an older version. :(

**Comment by fat** [comment]
this only happens on windows btw

**Comment by nfroidure** [comment]
@RobeeeJay this is an Emscripten issue. Indeed, Emscripten set up a catchall for handling exceptions, i don't know if there is a way to disable it or if there already is an issue for that. You should look that way, maybe that some changes in the Emscripten build command could solve this issue. https://github.com/nfroidure/ttf2woff2/blob/master/package.json#L22

**Comment by nfxpnk** [comment]
@nfroidure 
file `node_modules\gulp-iconfont\node_modules\gulp-ttf2woff2\node_modules\ttf2woff2\jssrc\ttf2woff2.js`
problem line is
`buffer=new ArrayBuffer(TOTAL_MEMORY);`
only when TOTAL_MEMORY = 536870912;
`var TOTAL_MEMORY=Module["TOTAL_MEMORY"]||536870912;`

as a workaround I've changed 536870912 to 136870912 and it seems to be working

i'm on Windows 10 64bit

gulp --version
[10:00:37] CLI version 3.9.0
[10:00:37] Local version 3.9.1

npm --version
2.14.12

node --version
v4.2.4
