### ISSUE TITLE
I get these error on window7

### ISSUE THREAD

**Issue by songyihong** [nfroidure/ttf2woff2#29]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'make' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'premake', 'make', 'postmake' ]
5 info premake ttf2woff2@2.0.3
6 info make ttf2woff2@2.0.3
7 verbose unsafe-perm in lifecycle true
8 info ttf2woff2@2.0.3 Failed to exec make script
9 verbose stack Error: ttf2woff2@2.0.3 make: `node-gyp build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid ttf2woff2@2.0.3
11 verbose cwd D:\ttf2woff2
12 error Windows_NT 6.1.7601
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "make"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error ttf2woff2@2.0.3 make: `node-gyp build`
17 error Exit status 1
18 error Failed at the ttf2woff2@2.0.3 make script 'node-gyp build'.
18 error This is most likely a problem with the ttf2woff2 package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node-gyp build
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ttf2woff2
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ttf2woff2
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

\node-gyp\src\win_delay_load_hook.c(34): error C2373:  __pfnDliNotifyHook2 define repeat;

**Comment by nfroidure** [comment]
Thanks for reporting the error but i do not debug windows platform. Feel free to PR if you end up resolving this issue.

**Comment by jedateach** [comment]
I'm seeing this on Mac and Redhat also.

```
$:/.../node_modules/grunt-webfont/node_modules/ttf2woff2 (master)$ "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.4.5 | linux | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp http GET https://nodejs.org/dist/v4.4.5/node-v4.4.5-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:831:8)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:267:9)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at TLSSocket.emit (events.js:169:7)
gyp ERR! stack     at connectErrorNT (net.js:996:8)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /.../node_modules/grunt-webfont/node_modules/ttf2woff2
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```
