### ISSUE TITLE
ttf2woff2.js seems to be detected as a virus 

### ISSUE THREAD

**Issue by deepu105** [nfroidure/ttf2woff2#30]
The content of the file in repo looks a bit suspicious as well with a lot of allocation code

![image](https://cloud.githubusercontent.com/assets/1107223/20455412/c67e22a6-ae5b-11e6-862e-5898aac2c88b.png)

**Comment by nfroidure** [comment]
https://github.com/nfroidure/ttf2woff2/issues/17
