### ISSUE TITLE
Install fails but npm proceeds as normal

### ISSUE THREAD

**Issue by SeanHayes** [nfroidure/ttf2woff2#31]
I didn't have Python installed in my Docker image so I got this error:
```
> ttf2woff2@2.0.3 install /srv/web/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.9.12-moby
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/web/node_modules/ttf2woff2
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

but I didn't notice because I'm installing a lot of stuff and `npm install` continued on like there was no problem. How do I get npm to bail out when this happens? Is this package misconfigured, or is there an npm flag I have to set? It seems like that should be the default behavior when you don't have the needed dependencies.

**Comment by nfroidure** [comment]
This package fallbacks to a JS version compiled with Emscripten, this why compilation failures aren't considered as fatal errors.

**Comment by SeanHayes** [comment]
Does that mean it's supposed to work even when node-gyp fails?

**Comment by nfroidure** [comment]
Yes, it should work but be much slower.

**Comment by SeanHayes** [comment]
So, I guess my original issue was a bug with the Emscripten build rather than a build error. I was converting a custom web font to woff2 and it was outputting a corrupt file that was 8192 bytes, instead of the 1812 bytes as was correctly generated by the node-gyp build. If this is an unknown bug I'll post a new Issue with steps to reproduce.

The corrupt woff2 caused the following message in my browser's console:

> Failed to decode downloaded font: https://development.example.com/assets/dist/iconfont/iconfont.woff2?2f88787688c881bbed921cd74da004f2
(index):1 OTS parsing error: incorrect file size in WOFF header
