### ISSUE TITLE
node-gyp  error on ttf2woff2

### ISSUE THREAD

**Issue by paulvandrunen** [nfroidure/ttf2woff2#37]
Hi in our Bamboo server and also when trying to install we get a node-gyp error. Anyone have a solution for this.

`npm install -g ttf2woff2
/usr/local/bin/ttf2woff2 -> /usr/local/lib/node_modules/ttf2woff2/bin/ttf2woff2.js

> ttf2woff2@2.0.3 install /usr/local/lib/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

+ ttf2woff2@2.0.3
added 105 packages in 28.948s`

**Comment by kibray** [comment]
Hi, I got the same error, have you find a way to solve this issue? @paulvandrunen

**Comment by RevealedFrom** [comment]
I am getting the exact same error too, both on Ubuntu and Windows.

I am trying to install [summernote](https://github.com/summernote), which uses `grunt-webfont` which in turn uses `ttf2woff2`.

Any help would be much appreciated. Thanks.

**Comment by hzsrc** [comment]
Got the same error. It was caused by the 'install' script in package.json :  (node-gyp rebuild > builderror.log) || (exit 0)
This seems not needed , it can run without executing this script command. 
But when I run `npm install` in a auto-build command on a server by jenkins, this may cause a crashing, and then jenkins failed.

**Comment by iwan-uschka** [comment]
The reason could be an incompatible version of python (3+). As a workaround i use a project based version of python (2.7.11). I don't have any idea of python so maybe i did it the ugly way:
- add "python = ${PWD}/path/within/project/python-2.7.11/bin/python" to `.npmrc` at project root level
- put python into this specific directory, i did it like this

```
#!/bin/bash

PROJECT_DIR="${PWD}"

# install python 2.7.11 locally
rm -rf path/within/project/python_src
rm -rf path/within/project/python-2.7.11
mkdir -p path/within/project/python_src
cd path/within/project/python_src
wget https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
tar zxfv Python-2.7.11.tgz
find Python-2.7.11 -type d | xargs chmod 0755
cd Python-2.7.11
./configure --prefix=${PROJECT_DIR}/path/within/project/python-2.7.11
make && make install
cd $PROJECT_DIR
rm -rf path/within/project/python_src
```

**Comment by zuo305** [comment]
In my opinion, I found it is running well in Node 10, but failed in Node 12, I am using Python and already tried "window build tools".

**Comment by anazhd** [comment]
> In my opinion, I found it is running well in Node 10, but failed in Node 12, I am using Python and already tried "window build tools".

yeah seems like it. I'd rather fall back to Node 10 than depending on Python 2+
