### ISSUE TITLE
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation

### ISSUE THREAD

**Issue by nfxpnk** [nfroidure/ttf2woff2#45]
npm install ttf2woff2

ttf2woff2@2.0.3 install H:\projects\gulp\node_modules\ttf2woff2
(node-gyp rebuild > builderror.log) || (exit 0)

Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd H:\projects\gulp\node_modules\ttf2woff2
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

ttf2woff2@2.0.3
updated 1 package and audited 10148 packages in 16.24s
found 8 vulnerabilities (4 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by Zhantrywei** [comment]
1. install python27 url: https://www.python.org/downloads/release/python-2718/
2. npm install --global windows-build-tools
