### ISSUE TITLE
CentOS npm install ttf2woff2 Error

### ISSUE THREAD

**Issue by iamtang** [nfroidure/ttf2woff2#47]
![image](https://user-images.githubusercontent.com/13829341/55535656-63e81180-56ea-11e9-9a63-7a2d3c57c940.png)

**Comment by av1v3k** [comment]
Same issue with webfonts-generator npm package depending on ttf2woff2.

Do not know whether ttf2woff2 can alone be upgraded as it is a dependency for webfonts-generator package.

NODE: 12.18.3
NPM: 6.14.6

![image](https://user-images.githubusercontent.com/1721339/126255753-f505d558-b360-44bc-87c4-90e162aa30c2.png)

**Comment by pioug** [comment]
@iamtang We can't offer any help for Node 8 support.

@av1v3k This was fixed https://github.com/nfroidure/ttf2woff2/issues/49 already, please use the latest version.
