### ISSUE TITLE
npm audit - HIGH - Arbitrary File Overwrite

### ISSUE THREAD

**Issue by webjohan** [nfroidure/ttf2woff2#48]
Sub dependency of node-gyp
 "node-gyp": "^3.7.0"
package tar has a High warning for dependency (tar) in npm audit.

npm audit security report
High : Arbitrary File Overwrite
Package : tar
Path: (* >) ttf2woff2 > node-gyp > tar

**Comment by Finesse** [comment]
The 4.0.0 version of `node-gyp` was released recently and it fixes the audit issue

**Comment by andersk** [comment]
ttf2woff2@4.0.0 now depends node-gyp@^7.1.2, so this can be closed.
