### ISSUE TITLE
Woff 2 Woff2

### ISSUE THREAD

**Issue by tomgallagher** [nfroidure/ttf2woff2#52]
Hi

I'm using this for TTF fonts, it has been very useful, thanks.

I would also like to convert WOFF to WOFF2. I'm a bit of a beginner with this. I'm assuming that your package only accepts TTF inputs. Do you happen to know how to do it? I can't find any node packages.

Thanks

Tom

**Comment by tomgallagher** [comment]
I was thinking that WOFF2 is only WOFF with Brotli compression, but I didn't want to just go ahead and do that when I don't really know what I'm doing!

**Comment by nfroidure** [comment]
Out of this project's scope sorry
