### ISSUE TITLE
AVG detecting HTML/Framer virus in ttf2woff2.js

### ISSUE THREAD

**Issue by gilesbutler** [nfroidure/ttf2woff2#7]
Hey Guys,

I presume this is just AVG getting it wrong but wanted to double check anyway.

<img width="733" alt="screen shot 2015-07-23 at 14 25 00" src="https://cloud.githubusercontent.com/assets/790734/8857255/d0639aa0-3146-11e5-98e3-3cbb9752c072.png">

Thanks

**Comment by nfroidure** [comment]
Hi.

I think AVG indeed is wrong, can't imagine the Emscripten guys appending viruses to builds ;).

You probably should report this false positive to AVG's maintainers.

**Comment by gilesbutler** [comment]
Ha yep thought so too, just thought I'd mention it :)

I checked on AVG's forums and looks like it's a common problem with other programs but they're support guys don't do anything about it!

**Comment by nfroidure** [comment]
Yep, it worth mentionning. Let's hope people will search issues ;).

**Comment by dudewad** [comment]
@gilesbutler Do you have a link to that thread? I'd like to chime in that this is silly, maybe one more +1 will make them fix it!

**Comment by gilesbutler** [comment]
@dudewad no sorry, I think I just googled it or searched on their forums. It's worth a try posting something else though.
