### ISSUE TITLE
cc1plus: Error: unrecognized command line option “-std=gnu++1y”

### ISSUE THREAD

**Issue by WuQiuYang** [nfroidure/ttf2woff2#77]
## Issue

I'm a gentledev I:
- [ ] fully read the README recently
- [ ] searched for existing issues
- [ ] checked I'm up to date with the latest version of the project

### Expected behavior

build error
![image](https://user-images.githubusercontent.com/38161177/145758185-2b5c3778-a686-48fd-afa6-ff44ed2f1b80.png)

### Debugging informations
- `node -v` result:
```
v12.16.1
```

- `npm -v` result:
```
<paste here>
```
If the result is lower than 14, there is
 poor chances I even have a look to it. Please,
 use the last [NodeJS LTS version](https://nodejs.org/en/).

### Use cases

- [ ] I will/did implement the feature

**Comment by pioug** [comment]
The CI of this project runs without error on Node v12, on both macOS and Ubuntu. Your best shot is using the same tools as the CI because it's very unlikely that someone will fix the issue your have reported.
